// examples/vue/src/components/Editor.vue
<script lang="ts" setup>
import { useEditor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import { codeBlock } from '../../../..'

const editor = useEditor({
  content: '<p>@vueditor/tiptap-extension-code-block</p>',
  extensions: [
    StarterKit.configure({
      codeBlock:false
    }),
    codeBlock
  ],
})
</script>

<template>
  <div class="editor">
    <EditorContent :editor="editor" />
  </div>
</template>

<style lang="scss">
.editor {
  box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);

  .tiptap {
    padding: 24px 64px;

    &:focus-visible {
      outline: none;
    }
  }
}
</style>

// examples/react/src/Editor.tsx
import { EditorProvider } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import tsx from 'shiki/langs/tsx.mjs'
import githubDark from 'shiki/themes/github-dark.mjs'
import githubLight from 'shiki/themes/github-light.mjs'
import { codeBlock } from '../../..'
import './Editor.scss'

// define your extension array
const extensions = [StarterKit.configure({
  codeBlock: false,
}), codeBlock.configure({
  themes: {
    light: githubLight,
    dark: githubDark,
  },
  languages: [tsx],
})]
const content = '@vueditor/tiptap-extension-code-block'

export default function Editor() {
  return (
    <div className="editor">
      <EditorProvider extensions={extensions} content={content}>

      </EditorProvider>
    </div>
  )
}
